### ISSUE TITLE
RuntimeError: set_storage_offset is not allowed on Tensor created from .data or .detach()

### ISSUE THREAD

**Issue by jrothschild33** [Shawn1993/cnn-text-classification-pytorch#25]
* 问题1：
```
Traceback (most recent call last):
  File "/cnn-text-classification-pytorch/main.py", line 112, in <module>
    train.train(train_iter, dev_iter, cnn, args)
  File "/cnn-text-classification-pytorch/train.py", line 25, in train
    feature.data.t_(), target.data.sub_(1)  # batch first, index align
RuntimeError: set_storage_offset is not allowed on Tensor created from .data or .detach()

Process finished with exit code 1
```
* 问题1解决：将【2处】`feature.data.t_(), target.data.sub_(1)`替换为：
```
 feature = feature.data.t()
 target = target.data.sub(1) 
```

* 问题2：
```
Traceback (most recent call last):
  File "/cnn-text-classification-pytorch/main.py", line 112, in <module>
    train.train(train_iter, dev_iter, cnn, args)
  File "/cnn-text-classification-pytorch/train.py", line 43, in train
    loss.data[0],
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

Process finished with exit code 1
```
* 问题2解决：将【2处】`loss.data[0]`替换为：`loss.item()`

**Comment by inkyusa** [comment]
Hope this helps!
https://github.com/inkyusa/cnn-text-classification-pytorch/commit/6dfefe7ae442d982d010969f4c1a7f1bd3125576

**Comment by Shawn1993** [comment]
感谢详细的问题报告和解决方案! 

你提到的两个问题在最新代码中都已经修复:

**问题1**: `RuntimeError: set_storage_offset is not allowed on Tensor created from .data or .detach()`
- ✅ 已修复: 移除了 `feature.data.t_()` 和 `target.data.sub_(1)` 的原地操作
- 现在直接使用 tensor 而不是通过 `.data` 属性

**问题2**: `IndexError: invalid index of a 0-dim tensor`
- ✅ 已修复: 所有 `loss.data[0]` 都已替换为 `loss.item()`

此外还修复了其他兼容性问题:
- 修复了 `size_average` 废弃警告
- 添加了 `torch.no_grad()` 上下文
- 添加了梯度裁剪
- 修复了 early stopping 逻辑

请更新到最新代码,所有问题都已解决!

**Comment by Shawn1993** [comment]
Thanks for the detailed bug report and solutions!

Both issues you mentioned have been fixed in the latest code:

**Issue 1**: `RuntimeError: set_storage_offset is not allowed on Tensor created from .data or .detach()`
- ✅ Fixed: Removed in-place operations `feature.data.t_()` and `target.data.sub_(1)`
- Now directly using tensors without the `.data` attribute

**Issue 2**: `IndexError: invalid index of a 0-dim tensor`
- ✅ Fixed: All `loss.data[0]` replaced with `loss.item()`

Additional compatibility fixes:
- Fixed `size_average` deprecation warning
- Added `torch.no_grad()` context
- Added gradient clipping
- Fixed early stopping logic

Please update to the latest code, all issues are resolved!
